name: Test and deploy

on:
  workflow_dispatch:

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run JUnit Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build

      - name: Trigger Deployment Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
        
